import array as ar

# Create an array of 10 integers using range()
array_var = ar.array('i', range(10))
print("Type of array_var is:", type(array_var))

# Print the values generated by range() function
print("The array will include: ", list(range(10)))



